### ISSUE TITLE
Official release

### ISSUE THREAD

**Issue by vkhodygo** [jenetics/lattices#1]
Hi @jenetics 

First of all, thank you for your efforts, it's much appreciated.
Do you have any thoughts regarding renaming your fork (say, Remington) and publishing it as a proper project via Maven or Jitpack.

I'm pretty sure a lot of legacy projects would benefit from that.

**Comment by jenetics** [comment]
Now available under https://search.maven.org/artifact/io.jenetics/colt/2.0.0/jar
